block.10002=minecraft:water
# Assign ID 10003 to all types of leaves and vines
block.10003=#minecraft:leaves minecraft:vine

# Assign ID 10004 to all grass, flowers, and ferns
block.10004=#minecraft:tall_flowers #minecraft:small_flowers minecraft:grass minecraft:tall_grass minecraft:fern minecraft:large_fern